name: Checkbox Workflow

on:
  workflow_dispatch:
    inputs:
      admin_line:
        description: 'Admin Roles'
      admin1:
        type: boolean
        description: by.yms.traileractivity.view
      admin2:
        type: boolean
        description: by.yms.traileractivity.operate
      admin3:
        type: boolean
        description: by.yms.traileractivity.manage
      admin4:
        type: boolean
        description: user.read
      admin5:
        type: boolean
        description: plat.lui.portal.settings.categories.yms-settings-operations-category.write
      admin6:
        type: boolean
        description: plat.lui.portal.settings.categories.yms-settings-operations-category.read
      admin7:
        type: boolean
        description: plat.lui.portal.settings.categories.yms-settings-operations-category.groups.yms-settings-operations-yard-group.write
      admin8:
        type: boolean
        description: plat.lui.portal.settings.categories.yms-settings-operations-category.groups.yms-settings-operations-yard-group.read
      yard_line:
        description: 'Yard Roles'
      yard1:
        type: boolean
        description: by.yms.traileractivity.view
      yard2:
        type: boolean
        description: by.yms.traileractivity.operate
      carrier_admin:
        description: 'carrier_admin Roles'
      carrier_admin1:
        type: boolean
        description: by.yms.carrierframework.view
      carrier_admin2:
        type: boolean
        description: by.yms.carrierframework.operate
      carrier_admin3:
        type: boolean
        description: by.yms.carrierframework.manage
      carrier_operator:
        description: 'carrier_operator Roles'
      carrier_operator1:
        type: boolean
        description: by.yms.carrierframework.view
      carrier_operator2:
        type: boolean
        description: by.yms.carrierframework.operate

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tasks
        run: |
          if [ "${{ github.event.inputs.use-emoji1 }}" == "true" ]; then
            echo "Option 1 is selected."
          fi

          if [ "${{ github.event.inputs.use-emoji2 }}" == "true" ]; then
            echo "${{ github.event.inputs.use-emoji2 }}"
          fi
