name: Checkbox Workflow

on:
  workflow_dispatch:
    inputs:
      option1:
        description: 'Option 1'
        required: false
        default: 'false'
      use-emoji1:
        type: boolean
        description: Option 1
      use-emoji2:
        type: boolean
        description: Option 2


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tasks
        run: |
          if [ "${{ github.event.inputs.use-emoji1 }}" == "true" ]; then
            echo "Option 1 is selected."
          fi

          if [ "${{ github.event.inputs.emoji2 }}" == "true" ]; then
            echo "Option 2 is selected."
          fi
