name: Checkbox Workflow

on:
  push:
    branches:
      - tdm


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tasks
        run: |
          sas="123450"
          echo "ABC=$sas" >> "${GITHUB_ENV}"

      - name: Print
        run: |
          echo "${{ env.ABC }}"
