name: Checkbox Workflow

on:
  push:
    branches:
      - tdm


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tasks
        run: |
          echo ::add-mask::$sas
          sas=$(echo "tdm")
          echo ::add-mask::$sas
          echo "ABC=$sas" >> "${GITHUB_ENV}"

      - name: Print
        if: ${{ env.ABC == 'tdmd'}}
        run: |
          echo "${{ env.ABC }}"
