name: Node.js CI

on:
  push:
    branches: [ test1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Install
      run: |
        npm ci
    
    
    - name: Tar the production build folder, manifest.json, and env.ejs template

      run: |

        tar -cvf production.tar index.js package*.json

#ab
    - name: Publish the package and an artifact to Github Releases

      id: release-checks

      continue-on-error: true

      env:

        GITHUB_TOKEN: "${{ steps.get_workflow_token.outputs.token }}"

      run: |

        npm run release -- minor --verbose --ci