name: Node.js CI

on:
  push:
    branches: [ main ]
env:
  TOKEN: ${{ secrets.TOKEN }}

#jobs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v4
      id: get_workflow_token
      with:
        repo-token: ${{ secrets.TOKEN }}


    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Install
      run: |
        npm ci
    
    
    - name: Build

      run: |

        tar -cvf production.tar index.js package*.json

#
    - name: Publish the package and an artifact to Github Releases
      env:
        # GITHUB_TOKEN: ${{env.TOKEN}}
        GITHUB_TOKEN: ${{github.token}}
      id: release-checks
      run: |
        git config --global user.email "sdivyanshu105@gmail.com"
        git config --global user.name "Divyanshu"
        npm run release minor --verbose --ci

